### ISSUE TITLE
JS.ORG Tutorial

### ISSUE THREAD

**Issue by indus** [tangshuang/nautil#1]
@tangshuang 
I have seen you have written a [tutorial](https://www.tangshuang.net/7603.html) about the usage of JS.ORG.
Nice - but the is one mistake. The service isn't operated from the USA but Germany (and GB). I tend to process the requests in the aftrenoon. Roughly 4 p.m. CET.

I was unsure the contact form at the end really send my message...

**Comment by tangshuang** [comment]
@indus O sorry, I did not know that really.

Thank you for your works on this project.👍
